config/routes.rb
Rails.application.routes.draw do
  get 'pets',          to: 'pets#index'
  get 'pets/new',      to: 'pets#new', as: :new_pet
  post 'pets',         to: 'pets#create'

  get 'pets/:id',      to: 'pets#show', as: :pet

  get 'pets/:id/edit', to: 'pets#edit', as: :edit_pet
  patch 'pets/:id',    to: 'pets#update'

  delete 'pets/:id',   to: 'pets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w[dog cat tiger elephant iguana]

  validates :species, :address, :date_found, presence: true
  validates :species, inclusion: { in: SPECIES }

  def count_days
    (Date.today - self.date_found).round
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[show edit update destroy]

  def index
    @pets = Pet.all
    # index.html.erb
  end

  def show
    # => show.html.erb
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:species, :address, :date_found)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostKitty</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for(@pet) do |f| %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :address %>
  <%= f.input :date_found, html5: true %>
  <%= f.submit class: 'btn btn-primary mt-3' %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit info of <%= @pet.species %></h1>
<%= render 'form' %>

app/views/pets/index.html.erb
<h1>All lost pets</h1>

<ul>
  <% @pets.each do |pet| %>
    <li><%= pet.species.capitalize %> - found <%= pet.count_days %> days ago - <%= link_to 'See more', pet_path(pet) %></li>
  <% end %>
</ul>

<p>You found a pet?<br>
<%= link_to 'Declare it', new_pet_path, class: 'btn btn-primary' %>
</p>

app/views/pets/new.html.erb
<h1>Indicate info about the pet you found</h1>
<%= render 'form' %>

app/views/pets/show.html.erb
<div class="container">
  <h1><%= @pet.species.upcase %></h1>
  <p>Found on: <%= @pet.date_found %></p>
  <p>Address: <%= @pet.address %></p>

  <p><%= link_to 'Back to lost pets', pets_path, class: 'btn btn-primary' %></p>
  <p><%= link_to 'Edit', edit_pet_path(@pet), class: 'btn btn-outline-primary' %></p>
  <p><%= link_to 'Delete', pet_path(@pet), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-primary' %></p>
</div>